create database Customer_behavior;
use Customer_behavior;
select * from customer limit 10;

-- Business Question for analysis.

-- Q1. What is the total revenue generated by male vs female customer.

select gender,sum(purchase_amount) as total_revenue from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than average purchase amount and count also?

-- customer_id with their purchase amount who have spent more than avg. purchase amount.

select customer_id, purchase_amount from customer
where discount_applied = 'Yes'and purchase_amount >= (select avg(purchase_amount) from customer);

-- total no. of customer total who have spent more than avg. purchase amount.
select count(customer_id) from customer
where discount_applied = 'Yes'and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3 What are the top 5 products with the highest average review rating.

select item_purchased, round(avg(review_rating),2) as Average_Product_Rating from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase Amount between standard and express shipping.

select distinct(shipping_type) from customer;

select shipping_type, avg(purchase_amount) as average_puchase_amount from customer
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type;

-- Q5.  Do subscribe customers spend more? Compare average spend and total revenue between subscribeers and non-subscribers?

select count(customer_id),subscription_status, round(avg(purchase_amount),2) as purchase_amount,
sum(purchase_amount) as total_revenue from customer
group by subscription_status
order by total_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied?

select item_purchased, 
round(((sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*))*100),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

-- Q7. Segment customer into new, returning, and loyal based on their total
-- number of previous , purchase, and show the count of each segment.  

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'NEW'
    when previous_purchases between 2 and 10 then 'RETURNING'
    else 'LOYAL'
    end as customer_segment
from customer
)

select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment;


-- Q8. What are the top three most purchased products within each category?

with item_count as (
select category,item_purchased, count(*) as total_orders,
row_number() over(partition by category order by count(*) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank,category, item_purchased,total_orders
from item_count
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select subscription_status, count(*) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10.  what are the revenue contributtion according to each age group?
select age_group, sum(purchase_amount) as total_revenue  from customer
group by age_group
order by total_revenue desc;